import { random } from "lodash";

export const allFormats = [
  {
    "1v1": "1v1",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lcextended: "LC (Extended)",
    lc: "LC",
    lclevel100: "LC Level 100",
    randombattle: "Random Battle",
    middlecup: "Middle Cup",
    monotype: "Monotype",
    nfe: "NFE",
    nu: "NU",
    nintendocup1997: "Nintendo Cup 1997",
    nc1997: "NC 1997",
    nc1999: "NC 1997",
    petitcup: "Petit Cup",
    pikacup: "Pika Cup",
    tradebacksou: "OU (Tradebacks)",
    pu: "PU",
    stabmons: "STABmons",
    stadiumou: "OU (Stadium)",
    tradebacksou: "OU (Tradebacks)",
    zu: "ZU",
  },
  {
    "1v1": "1v1",

    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    nfe: "NFE",
    pu: "PU",
    nu: "NU",
    zu: "ZU",
  },
  {
    "1v1": "1v1",
    doublesou: "Doubles OU",
    ou: "OU",
    nu: "NU",
    pu: "PU",
    zu: "ZU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    adv200: "ADV 200",
  },
  {
    anythinggoes: "Anything Goes",
    doublesou: "Doubles OU",
    nu: "NU",
    pu: "PU",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
  },
  {
    "1v1": "1v1",
    doublesou: "Doubles OU",
    dreamworldou: "OU (Dreamworld)",
    nu: "NU",
    pu: "PU",
    ru: "RU",
    zu: "ZU",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
    vgc2011: "VGC 2011",
    vgc2012: "VGC 2012",
  },
  {
    "1v1": "1v1",
    almostanyability: "Almost Any Ability",
    anythinggoes: "Anything Goes",
    balancedhackmons: "Balanced Hackmons",
    battlespotdoubles: "Battle Spot Doubles",
    battlespotsingles: "Battle Spot Singles",
    battlespottriples: "Battle Spot Triples",
    cap: "CAP",
    doublesou: "Doubles OU",
    middlecup: "Middle Cup",
    nu: "NU",
    ou: "OU",
    pu: "PU",
    purehackmons: "Pure Hackmons",
    ru: "RU",
    stabmons: "STABmons",
    vgc2014: "VGC 2014",
    vgc2016: "VGC 2016",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
    zu: "ZU",
  },
  {
    "1v1": "1v1",
    anythinggoes: "Anything Goes",
    balancedhackmons: "Balanced Hackmons",
    battlespotdoubles: "Battle Spot Doubles",
    battlespotsingles: "Battle Spot Singles",
    cap: "CAP",
    doublesou: "Doubles OU",
    letsgoou: "Let's Go! OU",
    mixandmega: "Mix and Mega",
    nfe: "NFE",
    nu: "NU",
    pu: "PU",
    ru: "RU",
    vgc2017: "VGC 2017",
    vgc2018: "VGC 2018",
    vgc2019: "VGC 2019",
    zu: "ZU",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
  },
  {
    "1v1": "1v1",
    "2v2doubles": "2v2 Doubles",
    almostanyability: "Almost Any Ability",
    balancedhackmons: "Balanced Hackmons",
    battlestadiumsingles: "Battle Stadium Singles",
    battlespotdoubles: "Battle Spot Doubles",
    bdspou: "BDSP OU",
    camomons: "Camomons",
    cap: "CAP",
    doublesou: "Doubles OU",
    godlygift: "Godly Gift",
    mixandmega: "Mix and Mega",
    nationaldex: "National Dex",
    nationaldexag: "National Dex Anything Goes",
    nationaldexmonotype: "National Dex Monotype",
    nationaldexru: "National Dex RU",
    nationaldexuu: "National Dex UU",
    nfe: "NFE",
    nu: "NU",
    pu: "PU",
    ru: "RU",
    stabmons: "STABmons",
    vgc2020: "VGC 2020",
    vgc2021: "VGC 2021",
    vgc2022: "VGC 2022",
    zu: "ZU",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
  },
  {
    "1v1": "1v1",
    almostanyability: "Almost Any Ability",
    anythinggoes: "Anything Goes",
    balancedhackmons: "Balanced Hackmons",
    battlestadiumsingles: "Battle Stadium Singles",
    cap: "CAP",
    doublesou: "Doubles OU",
    inheritance: "Inheritance",
    mixandmega: "Mix and Mega",
    monotype: "Monotype",
    nationaldex: "National Dex",
    nationaldexdoubles: "National Dex Doubles",
    nationaldexmonotype: "National Dex Monotype",
    nationaldexru: "National Dex RU",
    nationaldexubers: "National Dex Ubers",
    nationaldexuu: "National Dex UU",
    nfe: "NFE",
    nu: "NU",
    partnersincrime: "Partners in Crime",
    pu: "PU",
    randombattle: "Random Battle",
    ru: "RU",
    stabmons: "STABmons",
    ubersuu: "Ubers UU",
    vgc2023: "VGC 2023",
    vgc2024: "VGC 2024",
    zu: "ZU",
    ou: "OU",
    ubers: "Ubers",
    uu: "UU",
    lc: "LC",
    monotype: "Monotype",
  },
];
